services:
  - type: web
    name: space-explorer-api
    env: node
    buildCommand: npm install
    startCommand: npm run server
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
