import {useEffect,useState} from 'react';import {Glass,Hero,Button} from '../components/UI';import {astronauts,missions,planets} from '../data/planets';import {getApod,getSpaceNews,searchNasaImages} from '../services/api';
export function Missions(){return <><Hero eyebrow="Operations" title="Space Missions"/><div className="grid gap-4 md:grid-cols-3">{missions.map(m=><Glass key={m}><h2 className="text-xl font-bold">{m}</h2><p className="text-slate-300">Mission telemetry, objectives, timeline, and favorite actions.</p></Glass>)}</div></>}
export function Astronauts(){return <><Hero eyebrow="Crew" title="Astronauts"/><div className="grid gap-4 md:grid-cols-3">{astronauts.map(a=><Glass key={a}><h2 className="text-2xl font-black">{a}</h2><p className="text-slate-300">Expedition profile, specialties, and training record.</p></Glass>)}</div></>}
export function Gallery(){const [items,set]=useState([]);useEffect(()=>{searchNasaImages('nebula').then(set).catch(()=>set([]))},[]);return <><Hero eyebrow="NASA media" title="Image Gallery"/><div className="grid gap-4 md:grid-cols-3">{items.map((i,k)=><Glass key={k}><img loading="lazy" className="h-56 w-full rounded-2xl object-cover" src={i.links?.[0]?.href} alt={i.data?.[0]?.title}/><h2 className="mt-3 font-bold">{i.data?.[0]?.title}</h2></Glass>)}</div></>}
export function News(){const [items,set]=useState([]);useEffect(()=>{getSpaceNews().then(set).catch(()=>set([]))},[]);return <><Hero eyebrow="Live feed" title="Space News"/><div className="grid gap-4 md:grid-cols-2">{items.map(n=><Glass key={n.id}><h2 className="text-xl font-bold">{n.title}</h2><p className="text-slate-300">{n.summary}</p><a className="text-cyan-200" href={n.url}>Read source</a></Glass>)}</div></>}
export function Search(){const [q,setQ]=useState('Mars');const [items,setItems]=useState([]);const go=()=>searchNasaImages(q).then(setItems);const voice=()=>{const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(R){const r=new R();r.onresult=e=>setQ(e.results[0][0].transcript);r.start()}};return <><Hero eyebrow="Global + voice" title="Search the universe"/><Glass><input value={q} onChange={e=>setQ(e.target.value)} className="w-full rounded-2xl bg-white/10 p-4"/><div className="mt-4 flex gap-3"><Button onClick={go}>Search</Button><Button onClick={voice}>Voice Search</Button></div></Glass><div className="mt-6 grid gap-4 md:grid-cols-4">{items.map((i,k)=><img key={k} className="h-40 w-full rounded-2xl object-cover" src={i.links?.[0]?.href}/>)}</div></>}
export function Quiz(){return <><Hero eyebrow="Leaderboard ready" title="Space Quiz"/><div className="grid gap-4">{planets.slice(0,5).map((p,i)=><Glass key={p.slug}><h2 className="font-bold">Question {i+1}: Which planet is known as {p.summary.split(' ')[1]}?</h2><Button>Submit Answer</Button></Glass>)}</div></>}
export function Dashboard(){return <><Hero eyebrow="Admin" title="Mission Control Dashboard"/><div className="grid gap-4 md:grid-cols-3">{['Users','Favorites','Quiz Scores','API Health','Notifications','Content'].map(x=><Glass key={x}><h2 className="text-3xl font-black">{x}</h2><p className="text-slate-300">Role-protected management panel.</p></Glass>)}</div></>}
export function Favorites(){return <><Hero eyebrow="Saved" title="Favorites"/><Glass>MongoDB-backed saved planets, images, and missions appear here.</Glass></>}
export function Profile(){return <><Hero eyebrow="Account" title="Profile"/><Glass>Firebase authenticated profile with preferences, dark mode, and notification settings.</Glass></>}
export function About(){return <><Hero eyebrow="About" title="Built for curious explorers"><p>Educational, accessible, responsive, API-powered space discovery.</p></Hero></>}
export function Contact(){return <><Hero eyebrow="Contact API" title="Contact mission control"/><Glass><input className="mb-3 w-full rounded-xl bg-white/10 p-3" placeholder="Email"/><textarea className="w-full rounded-xl bg-white/10 p-3" placeholder="Message"/><Button>Send</Button></Glass></>}
export function Login(){return <><Hero eyebrow="Auth" title="Login / Register"/><Glass><input className="mb-3 w-full rounded-xl bg-white/10 p-3" placeholder="Email"/><input className="mb-3 w-full rounded-xl bg-white/10 p-3" placeholder="Password" type="password"/><Button>Continue</Button></Glass></>}
export function NotFound(){return <Hero eyebrow="404" title="Lost in deep space"><p>The coordinates you entered do not map to a known route.</p></Hero>}
export function ApodBanner(){const [a,set]=useState(null);useEffect(()=>{getApod().then(set).catch(()=>{})},[]);return a&&<Glass><h2>{a.title}</h2></Glass>}
